### PR TITLE
Add some cheap optimizations

### PR DESCRIPTION
**Pull request by svenstaro**
In my tests with a 2.2m-files strong list, my results were as such:

| trial | hyperfine time | file size |
| --- | -------------------| -----------|
| without this change | 3.390s | 3.4MiB
| with this change | 3.247s | 1.5MiB

so a free improvement of 4% and a stark decrease in file size. What's not to love?

### CODE REVIEW

**Comment by jonhoo** [comment]
Unfortunately this isn't _quite_ free. While you're right that it improves runtime marginally and binary size a decent amount, it's not great for compilation and debugging. `lto = "yes"` and `codegen-units = 1` both slow down compilation, and often a decent amount, yet seem to yield fairly little in terms of performance speed-up here. Perhaps it's not significant here given that this crate is already pretty small, but it'd be great if you could measure compile time differences too!

`panic = "abort"` is a bigger issue — it make debugging runtime errors much harder (since you get no backtraces). This means that if someone runs `proximity-sort` and runs into an issue, the only issue report we'll get is "it crashed", which isn't great. `panic = "abort"` also requires re-compiling all dependencies (since they must also be compiled with `panic = "abort"`), which is really annoying when using a shared cargo cache (e.g., by setting `CARGO_TARGET_DIR`). I suspect this is where the binary size decrease comes from (and not really the runtime perf.), and am not sure a file size reduction of 2MB is actually worth it?

**Comment by svenstaro** [comment]
You raise valid points but keep in mind that this is only for the release profile which you're probably not using for rapid development recompilation. However, I made some compilation benchmarks:

With my PR:
```
cargo clean && time cargo build --release
cargo build --release  16.07s user 0.59s system 111% cpu 14.962 total
```
without my PR:
```
cargo clean && time cargo build --release
cargo build --release  23.68s user 0.77s system 456% cpu 5.361 total
```

I'm removing the `panic = "abort"` thing as it only shrank the binary by `0.1MiB`.

**Review by jonhoo — APPROVED** [review]

**Comment by jonhoo** [comment]
That's true. I was certainly much more worried about `panic = "abort"` than the other two. A 3x compile time factor is pretty bad, but as you say since it's in release mode maybe it's fine.

**Comment by jonhoo** [comment]
Released in `1.0.7`.

**Pull request merged**
